"""Constants used in pyhs3."""

import logging

_LOGGER = logging.getLogger(__name__)

DEFAULT_ASCII_PORT = 11000
DEFAULT_HTTP_PORT = 80
DEFAULT_PASSWORD = "default"
DEFAULT_USERNAME = "default"

DEVICE_ZWAVE_BARRIER_OPERATOR = "Z-Wave Barrier Operator"
DEVICE_ZWAVE_BATTERY = "Z-Wave Battery"
DEVICE_ZWAVE_CENTRAL_SCENE = "Z-Wave Central Scene"
DEVICE_ZWAVE_DOOR_LOCK = "Z-Wave Door Lock"
DEVICE_ZWAVE_FAN_STATE = "Z-Wave Fan State"
DEVICE_ZWAVE_LUMINANCE = "Z-Wave Luminance"
DEVICE_ZWAVE_OPERATING_STATE = "Z-Wave Operating State"
DEVICE_ZWAVE_RELATIVE_HUMIDITY = "Z-Wave Relative Humidity"
DEVICE_ZWAVE_SENSOR_BINARY = "Z-Wave Sensor Binary"
DEVICE_ZWAVE_SENSOR_MULTILEVEL = "Z-Wave Sensor Multilevel"
DEVICE_ZWAVE_SWITCH = "Z-Wave Switch"
DEVICE_ZWAVE_SWITCH_BINARY = "Z-Wave Switch Binary"
DEVICE_ZWAVE_SWITCH_MULTILEVEL = "Z-Wave Switch Multilevel"
DEVICE_ZWAVE_TEMPERATURE = "Z-Wave Temperature"

DEVICE_INSTEON_SWITCH = "Insteon Dual-Band SwitchLinc On/Off"
DEVICE_INSTEON_SWITCH2 = "Insteon Outdoor ApplianceLinc"
DEVICE_INSTEON_SWITCH3 = "ApplianceLinc"
DEVICE_INSTEON_SWITCH_MULTILEVEL = "Insteon Dual-Band SwitchLinc Dimmer"


REASON_DISCONNECTED = "disconnected"
REASON_RECONNECTED = "reconnected"

STATE_CLOSED = "closed"
STATE_CLOSING = "closing"
STATE_CONNECTING = "connecting"
STATE_DISCONNECTED = "disconnected"
STATE_IDLE = "idle"
STATE_LISTENING = "listening"
STATE_OPEN = "open"
STATE_OPENING = "opening"
STATE_STOPPED = "stopped"

HS_UNIT_CELSIUS = "C"
HS_UNIT_FAHRENHEIT = "F"
HS_UNIT_LUX = "Lux"
HS_UNIT_PERCENTAGE = "%"

HASS_BINARY_SENSORS = [DEVICE_ZWAVE_SENSOR_BINARY]
HASS_COVERS = [DEVICE_ZWAVE_BARRIER_OPERATOR]
HASS_EVENTS = [DEVICE_ZWAVE_CENTRAL_SCENE]

ZWAVE_LIGHTS = [
    DEVICE_ZWAVE_SWITCH_MULTILEVEL,
    DEVICE_INSTEON_SWITCH_MULTILEVEL,
]
INSTEON_LIGHTS = [
    DEVICE_INSTEON_SWITCH_MULTILEVEL,
    "Insteon KeypadLinc V2 Dimmer Button A/Load",
]
HASS_LIGHTS = ZWAVE_LIGHTS + INSTEON_LIGHTS

HASS_LOCKS = [DEVICE_ZWAVE_DOOR_LOCK]
HASS_SENSORS = [
    DEVICE_ZWAVE_BATTERY,
    DEVICE_ZWAVE_FAN_STATE,
    DEVICE_ZWAVE_LUMINANCE,
    DEVICE_ZWAVE_TEMPERATURE,
    DEVICE_ZWAVE_OPERATING_STATE,
    DEVICE_ZWAVE_RELATIVE_HUMIDITY,
    DEVICE_ZWAVE_SENSOR_MULTILEVEL,
]

ZWAVE_SWITCHES = [DEVICE_ZWAVE_SWITCH, DEVICE_ZWAVE_SWITCH_BINARY]

INSTEON_SWITCHES = [
    DEVICE_INSTEON_SWITCH,
    DEVICE_INSTEON_SWITCH2,
    DEVICE_INSTEON_SWITCH3,
    "Insteon KeypadLinc V2 Dimmer Button B",
    "Insteon KeypadLinc V2 Dimmer Button C",
    "Insteon KeypadLinc V2 Dimmer Button D",
    "Insteon KeypadLinc V2 Dimmer Button E",
    "Insteon KeypadLinc V2 Dimmer Button F",
    "Insteon KeypadLinc V2 Dimmer Button G",
    "Insteon KeypadLinc V2 Dimmer Button H",
]

HASS_SWITCHES = ZWAVE_SWITCHES + INSTEON_SWITCHES
